// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplierScreening.Api.Data;

#nullable disable

namespace SupplierScreening.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SupplierScreening.Api.Models.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "US",
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Code = "PE",
                            Name = "Perú"
                        },
                        new
                        {
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Code = "MX",
                            Name = "México"
                        },
                        new
                        {
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Code = "BR",
                            Name = "Brasil"
                        },
                        new
                        {
                            Code = "ES",
                            Name = "España"
                        },
                        new
                        {
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Code = "PA",
                            Name = "Panamá"
                        },
                        new
                        {
                            Code = "GB",
                            Name = "Reino Unido"
                        },
                        new
                        {
                            Code = "DE",
                            Name = "Alemania"
                        },
                        new
                        {
                            Code = "FR",
                            Name = "Francia"
                        },
                        new
                        {
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Code = "RU",
                            Name = "Rusia"
                        },
                        new
                        {
                            Code = "IR",
                            Name = "Irán"
                        });
                });

            modelBuilder.Entity("SupplierScreening.Api.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("AnnualRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("LastEditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("LastEditedAt");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Av. Javier Prado 1234, San Isidro, Lima",
                            AnnualRevenue = 2500000.00m,
                            CommercialName = "Andina Trade",
                            CountryCode = "PE",
                            CreatedAt = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contacto@andinatrade.com",
                            LastEditedAt = new DateTime(2026, 1, 15, 12, 0, 0, 0, DateTimeKind.Utc),
                            LegalName = "Comercializadora Andina S.A.C.",
                            Phone = "+51 1 4567890",
                            TaxId = "20123456789",
                            Website = "https://www.andinatrade.com"
                        },
                        new
                        {
                            Id = 2,
                            Address = "1200 Brickell Ave, Miami, FL",
                            AnnualRevenue = 14750000.50m,
                            CommercialName = "GlobalLog",
                            CountryCode = "US",
                            CreatedAt = new DateTime(2026, 1, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@globallog.com",
                            LastEditedAt = new DateTime(2026, 1, 16, 12, 0, 0, 0, DateTimeKind.Utc),
                            LegalName = "Global Logistics Corporation",
                            Phone = "+1 305 5551234",
                            TaxId = "98765432101",
                            Website = "https://www.globallog.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Calle 13 #504 e/ D y E, Vedado, La Habana",
                            AnnualRevenue = 850000.00m,
                            CommercialName = "Amistur",
                            CountryCode = "CU",
                            CreatedAt = new DateTime(2026, 1, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ventas@amistur.cu",
                            LastEditedAt = new DateTime(2026, 1, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            LegalName = "Amistur Cuba S.A.",
                            Phone = "+53 7 8320000",
                            TaxId = "11223344556",
                            Website = "https://www.amistur.cu"
                        });
                });

            modelBuilder.Entity("SupplierScreening.Api.Models.Supplier", b =>
                {
                    b.HasOne("SupplierScreening.Api.Models.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
